/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JList;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sharvik
 */
public class MenuPanel extends javax.swing.JFrame {

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        userArgs = new ArrayList<>();
        proyArgs = new ArrayList<>();
        
        BufferedReader br;
        String line;
        
        try {
            br = new BufferedReader(new FileReader("usuarios.txt"));
            while((line = br.readLine()) != null) {
                for (String[] arg : userArgs) {
                    arg = line.split(":");
                    System.out.println(arg[0]);
                }
            }
            
            br.close();
            
            
            br = new BufferedReader(new FileReader("proyectos.txt"));
            
            /*while((line = br.readLine()) != null)
                for (String[] arg : proyArgs)
                    arg = line.split(":");
                    */
            br.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(proyArgs.get(0)[0]);
        Object[] column = new Object[4];
        for (String[] proyArg : proyArgs) {
            for (String string : proyArg) {
                System.out.println(string);
            }
            DefaultTableModel model = (DefaultTableModel) proyTab.getModel();
            model.addRow(column);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cobrarAllB = new javax.swing.JButton();
        cobrarB = new javax.swing.JButton();
        amountTitle = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        BagTitle = new javax.swing.JLabel();
        bagLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        proyTab = new javax.swing.JTable();
        mostrarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cobrarAllB.setText("Cobrar todo");
        cobrarAllB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarAllBActionPerformed(evt);
            }
        });

        cobrarB.setText("Cobrar");
        cobrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarBActionPerformed(evt);
            }
        });

        amountTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        amountTitle.setText("Tu saldo : ");

        amountLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountLabel.setText("0");

        BagTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BagTitle.setText("Fondo del proyecto : ");

        bagLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bagLabel.setText("0");

        proyTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Proyecto", "Fondo", "¿Cobrar?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(proyTab);

        mostrarB.setText("Mostrar");
        mostrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountTitle)
                        .addGap(18, 18, 18)
                        .addComponent(amountLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BagTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bagLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cobrarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cobrarAllB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountTitle)
                            .addComponent(amountLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BagTitle)
                            .addComponent(bagLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobrarAllB)
                    .addComponent(cobrarB)
                    .addComponent(mostrarB))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrarBActionPerformed

    private void mostrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBActionPerformed
        System.out.println("Mostrar");
        System.out.println(proyArgs.get(0)[0]);
        Object[] column = new Object[4];
        for (String[] proyArg : proyArgs) {
            for (String string : proyArg) {
                System.out.println(string);
            }
            DefaultTableModel model = (DefaultTableModel) proyTab.getModel();
            model.addRow(column);
        }

    }//GEN-LAST:event_mostrarBActionPerformed

    private void cobrarAllBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarAllBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrarAllBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JList lista = new JList();
                
                new MenuPanel().setVisible(true);
            }
        });
    }
    private ArrayList<String[]> userArgs;
    private ArrayList<String[]> proyArgs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BagTitle;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountTitle;
    private javax.swing.JLabel bagLabel;
    private javax.swing.JButton cobrarAllB;
    private javax.swing.JButton cobrarB;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mostrarB;
    private javax.swing.JTable proyTab;
    // End of variables declaration//GEN-END:variables
}
